In [3]:
import numpy as np

# Creating arrays


In [4]:
np.zeros(10) #1D array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(5, 2.3)

array([2.3, 2.3, 2.3, 2.3, 2.3])

In [7]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
a[3]

np.int64(4)

In [9]:
np.arange(10)# arrange the list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(1,100,11)

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

# Multidimentional arrays


In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
a= np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])

In [13]:
a[0,1]

np.int64(2)

In [14]:
a[2,1]=5

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 5, 9]])

In [16]:
a[2]# prints row

array([7, 5, 9])

In [17]:
a[2]=[1,2,3]
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [18]:
a[:,1]# prints column


array([2, 5, 2])

In [19]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

# Generate random Array

In [20]:
np.random.seed(2) #we fixed so we dont get any number
np.random.rand(4,6)#prints random arrays


array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
        0.33033482],
       [0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
        0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515, 0.85397529,
        0.49423684],
       [0.84656149, 0.07964548, 0.50524609, 0.0652865 , 0.42812233,
        0.09653092]])

In [21]:
np.random.randn(4,6)# we say numbers are normal (n)standard

array([[ 2.56570452e-01, -9.88779049e-01, -3.38821966e-01,
        -2.36184031e-01, -6.37655012e-01, -1.18761229e+00],
       [-1.42121723e+00, -1.53495196e-01, -2.69056960e-01,
         2.23136679e+00, -2.43476758e+00,  1.12726505e-01],
       [ 3.70444537e-01,  1.35963386e+00,  5.01857207e-01,
        -8.44213704e-01,  9.76147160e-06,  5.42352572e-01],
       [-3.13508197e-01,  7.71011738e-01, -1.86809065e+00,
         1.73118467e+00,  1.46767801e+00, -3.35677339e-01]])

In [22]:
np.random.randint(low=0,high=100, size=(5,4))

array([[70, 86, 70, 19],
       [56, 82,  1, 68],
       [40, 81, 61, 70],
       [97, 18, 84, 90],
       [87, 22, 43, 52]])

# Element Wise Operation

In [23]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
a*100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [26]:
b=a*4
b

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [27]:
a+ b

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [28]:
a*b

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324])

# compaarision operation

In [29]:
a>=2 #compare all elements of the a

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [30]:
a.min()
a.max()
a.mean()
a.sum()


np.int64(45)

# Multiplication
   ## vector vector multiplication(dot product)

   ## vector Matrix multiplication
   ## Matrix Matrix Multiplication

In [31]:
def vector_vector_multiplication(a,b):
    assert a.shape[0]== b.shape[0]
    n =  a.shape[0]
    result = 0.0
    for i in range(n):
        result= result + a[i]*b[i]    
    return result 


In [32]:
vector_vector_multiplication(a,b)

np.float64(1140.0)

In [33]:
a.dot(b)# its dot product very esaily

np.int64(1140)

In [34]:
U = np.array([[1,2,3,4],
         [4,5,6,5],
         [7,8,9,6],
        [7,8,9,6]])

In [35]:
U.shape

(4, 4)

In [36]:
v= np.arange(4)
v.shape

(4,)

In [37]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

In [38]:
matrix_vector_multiplication(U, v)

array([20., 32., 44., 44.])

In [39]:
U.dot(v)

array([20, 32, 44, 44])

# Idntity Matrix

In [40]:
I=np.eye(4)


In [41]:
I


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
p= np.random.randint(low=0,high=10, size=(4,4))
p

array([[5, 8, 3, 0],
       [0, 5, 7, 5],
       [0, 8, 6, 5],
       [1, 7, 4, 3]])

In [43]:
p.dot(I)# multiplying any  vectors with Identity matrix ,we will get the same vectors like multpliying  one b yany number

array([[5., 8., 3., 0.],
       [0., 5., 7., 5.],
       [0., 8., 6., 5.],
       [1., 7., 4., 3.]])

In [44]:
np.linalg.inv(I)# inverse should be equal rows and columns

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
s= np.array([[1,2,3,4],[1,2,3,4]])
s

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [51]:
s*2

array([[2, 4, 6, 8],
       [2, 4, 6, 8]])